//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy 的本地化字符串。
        /// </summary>
        internal static string AccurancyText {
            get {
                return ResourceManager.GetString("AccurancyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AC 的本地化字符串。
        /// </summary>
        internal static string ACText {
            get {
                return ResourceManager.GetString("ACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} Credits to your Account. 的本地化字符串。
        /// </summary>
        internal static string AddsCreditsToAccount {
            get {
                return ResourceManager.GetString("AddsCreditsToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds 的本地化字符串。
        /// </summary>
        internal static string AddsText {
            get {
                return ResourceManager.GetString("AddsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agility 的本地化字符串。
        /// </summary>
        internal static string AgilityText {
            get {
                return ResourceManager.GetString("AgilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Damage Reduction 的本地化字符串。
        /// </summary>
        internal static string AllDamageReductionText {
            get {
                return ResourceManager.GetString("AllDamageReductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All parcels have been collected. 的本地化字符串。
        /// </summary>
        internal static string AllParcelsCollected {
            get {
                return ResourceManager.GetString("AllParcelsCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A.Speed 的本地化字符串。
        /// </summary>
        internal static string ASpeedText {
            get {
                return ResourceManager.GetString("ASpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auction has already ended for this item. 的本地化字符串。
        /// </summary>
        internal static string AuctionEnded {
            get {
                return ResourceManager.GetString("AuctionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awakening already at maximum level. 的本地化字符串。
        /// </summary>
        internal static string AwakeningAtMaxLevel {
            get {
                return ResourceManager.GetString("AwakeningAtMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bag Weight 的本地化字符串。
        /// </summary>
        internal static string BagWeightText {
            get {
                return ResourceManager.GetString("BagWeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breaks on death 的本地化字符串。
        /// </summary>
        internal static string BreaksOnDeath {
            get {
                return ResourceManager.GetString("BreaksOnDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can be used on 的本地化字符串。
        /// </summary>
        internal static string CanBeUsedOn {
            get {
                return ResourceManager.GetString("CanBeUsedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot awaken this item. 的本地化字符串。
        /// </summary>
        internal static string CannotAwakenItem {
            get {
                return ResourceManager.GetString("CannotAwakenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot be used by Hero 的本地化字符串。
        /// </summary>
        internal static string CannotBeUsedByHero {
            get {
                return ResourceManager.GetString("CannotBeUsedByHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot be used on any item. 的本地化字符串。
        /// </summary>
        internal static string CannotBeUsedOnAnyItem {
            get {
                return ResourceManager.GetString("CannotBeUsedOnAnyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot be a Wedding Ring 的本地化字符串。
        /// </summary>
        internal static string CannotBeWeddingRing {
            get {
                return ResourceManager.GetString("CannotBeWeddingRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot buy your own items. 的本地化字符串。
        /// </summary>
        internal static string CannotBuyOwnItems {
            get {
                return ResourceManager.GetString("CannotBuyOwnItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot carry anymore gold. 的本地化字符串。
        /// </summary>
        internal static string CannotCarryAnymoreGold {
            get {
                return ResourceManager.GetString("CannotCarryAnymoreGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot cast {0} for another {1} seconds. 的本地化字符串。
        /// </summary>
        internal static string CannotCastSpell {
            get {
                return ResourceManager.GetString("CannotCastSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot consign this item. 的本地化字符串。
        /// </summary>
        internal static string CannotConsignItem {
            get {
                return ResourceManager.GetString("CannotConsignItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot repair this item. 的本地化字符串。
        /// </summary>
        internal static string CannotRepairItem {
            get {
                return ResourceManager.GetString("CannotRepairItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot sell this item. 的本地化字符串。
        /// </summary>
        internal static string CannotSellItem {
            get {
                return ResourceManager.GetString("CannotSellItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot cast {0} for another {1} seconds. 的本地化字符串。
        /// </summary>
        internal static string CantCastAnotherSeconds {
            get {
                return ResourceManager.GetString("CantCastAnotherSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t drop 的本地化字符串。
        /// </summary>
        internal static string CantDrop {
            get {
                return ResourceManager.GetString("CantDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t drop on death 的本地化字符串。
        /// </summary>
        internal static string CantDropOnDeath {
            get {
                return ResourceManager.GetString("CantDropOnDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t repair 的本地化字符串。
        /// </summary>
        internal static string CantRepair {
            get {
                return ResourceManager.GetString("CantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t sell 的本地化字符串。
        /// </summary>
        internal static string CantSell {
            get {
                return ResourceManager.GetString("CantSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t special repair 的本地化字符串。
        /// </summary>
        internal static string CantSpecialRepair {
            get {
                return ResourceManager.GetString("CantSpecialRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t store 的本地化字符串。
        /// </summary>
        internal static string CantStore {
            get {
                return ResourceManager.GetString("CantStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t trade 的本地化字符串。
        /// </summary>
        internal static string CantTrade {
            get {
                return ResourceManager.GetString("CantTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t upgrade 的本地化字符串。
        /// </summary>
        internal static string CantUpgrade {
            get {
                return ResourceManager.GetString("CantUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Character with this name already exists. 的本地化字符串。
        /// </summary>
        internal static string CharacterNameExists {
            get {
                return ResourceManager.GetString("CharacterNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Refine 的本地化字符串。
        /// </summary>
        internal static string CheckRefineText {
            get {
                return ResourceManager.GetString("CheckRefineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The class you selected does not exist.\n Contact a GM for assistance. 的本地化字符串。
        /// </summary>
        internal static string ClassDoesNotExist {
            get {
                return ResourceManager.GetString("ClassDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consignment Price 的本地化字符串。
        /// </summary>
        internal static string ConsignmentPriceText {
            get {
                return ResourceManager.GetString("ConsignmentPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consignment 的本地化字符串。
        /// </summary>
        internal static string ConsignmentText {
            get {
                return ResourceManager.GetString("ConsignmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created by Game Master 的本地化字符串。
        /// </summary>
        internal static string CreatedByGameMaster {
            get {
                return ResourceManager.GetString("CreatedByGameMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please give your creature a name. 的本地化字符串。
        /// </summary>
        internal static string CreatureNamePrompt {
            get {
                return ResourceManager.GetString("CreatureNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Chance 的本地化字符串。
        /// </summary>
        internal static string CriticalChanceText {
            get {
                return ResourceManager.GetString("CriticalChanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Damage: + {0} 的本地化字符串。
        /// </summary>
        internal static string CriticalDamageNoAdd {
            get {
                return ResourceManager.GetString("CriticalDamageNoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Damage 的本地化字符串。
        /// </summary>
        internal static string CriticalDamageText {
            get {
                return ResourceManager.GetString("CriticalDamageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + Right Click 的本地化字符串。
        /// </summary>
        internal static string CtrlRightClick {
            get {
                return ResourceManager.GetString("CtrlRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Curse 的本地化字符串。
        /// </summary>
        internal static string CurseText {
            get {
                return ResourceManager.GetString("CurseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DC 的本地化字符串。
        /// </summary>
        internal static string DCText {
            get {
                return ResourceManager.GetString("DCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deal cancelled.\r\nTo deal correctly you must face the other party. 的本地化字符串。
        /// </summary>
        internal static string DealCancelled {
            get {
                return ResourceManager.GetString("DealCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destroyed when dropped 的本地化字符串。
        /// </summary>
        internal static string DestroyedWhenDropped {
            get {
                return ResourceManager.GetString("DestroyedWhenDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has requested a divorce. 的本地化字符串。
        /// </summary>
        internal static string DivorceRequest {
            get {
                return ResourceManager.GetString("DivorceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Cross Half Moon. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseCrossHalfMoon {
            get {
                return ResourceManager.GetString("DoNotUseCrossHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Double Slash. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseDoubleSlash {
            get {
                return ResourceManager.GetString("DoNotUseDoubleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Half Moon. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseHalfMoon {
            get {
                return ResourceManager.GetString("DoNotUseHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Thrusting. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseThrusting {
            get {
                return ResourceManager.GetString("DoNotUseThrusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have enough gold to refine your {0}. 的本地化字符串。
        /// </summary>
        internal static string DontHaveGoldRefine {
            get {
                return ResourceManager.GetString("DontHaveGoldRefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downgrade 的本地化字符串。
        /// </summary>
        internal static string DowngradeText {
            get {
                return ResourceManager.GetString("DowngradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Rate 的本地化字符串。
        /// </summary>
        internal static string DropRateText {
            get {
                return ResourceManager.GetString("DropRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop 的本地化字符串。
        /// </summary>
        internal static string DropText {
            get {
                return ResourceManager.GetString("DropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Durability 的本地化字符串。
        /// </summary>
        internal static string DurabilityText {
            get {
                return ResourceManager.GetString("DurabilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        internal static string DurationText {
            get {
                return ResourceManager.GetString("DurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a guild name, length must be 3~20 characters. 的本地化字符串。
        /// </summary>
        internal static string EnterGuildName {
            get {
                return ResourceManager.GetString("EnterGuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the person you would like to mail. 的本地化字符串。
        /// </summary>
        internal static string EnterMailRecipient {
            get {
                return ResourceManager.GetString("EnterMailRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the guild you would like to go to war with. 的本地化字符串。
        /// </summary>
        internal static string EnterWarGuildName {
            get {
                return ResourceManager.GetString("EnterWarGuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp Rate 的本地化字符串。
        /// </summary>
        internal static string ExpRateText {
            get {
                return ResourceManager.GetString("ExpRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp 的本地化字符串。
        /// </summary>
        internal static string ExpText {
            get {
                return ResourceManager.GetString("ExpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flexibility: + {0} 的本地化字符串。
        /// </summary>
        internal static string FlexibilityNoAdd {
            get {
                return ResourceManager.GetString("FlexibilityNoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flexibility 的本地化字符串。
        /// </summary>
        internal static string FlexibilityText {
            get {
                return ResourceManager.GetString("FlexibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Freezing 的本地化字符串。
        /// </summary>
        internal static string FreezingText {
            get {
                return ResourceManager.GetString("FreezingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The gender you selected does not exist.\n Contact a GM for assistance. 的本地化字符串。
        /// </summary>
        internal static string GenderDoesNotExist {
            get {
                return ResourceManager.GetString("GenderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold Rate 的本地化字符串。
        /// </summary>
        internal static string GoldRateText {
            get {
                return ResourceManager.GetString("GoldRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold 的本地化字符串。
        /// </summary>
        internal static string GoldText {
            get {
                return ResourceManager.GetString("GoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to group with {0}? 的本地化字符串。
        /// </summary>
        internal static string GroupInviteMessage {
            get {
                return ResourceManager.GetString("GroupInviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use the \\ sign in a guild name! 的本地化字符串。
        /// </summary>
        internal static string GuildNameInvalid {
            get {
                return ResourceManager.GetString("GuildNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hand Weight 的本地化字符串。
        /// </summary>
        internal static string HandWeightText {
            get {
                return ResourceManager.GetString("HandWeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t deposited any items to refine your {0} with. 的本地化字符串。
        /// </summary>
        internal static string HaventDepositedRefine {
            get {
                return ResourceManager.GetString("HaventDepositedRefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health Recovery 的本地化字符串。
        /// </summary>
        internal static string HealthRecoveryText {
            get {
                return ResourceManager.GetString("HealthRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero created successfully. 的本地化字符串。
        /// </summary>
        internal static string HeroCreatedSuccessfully {
            get {
                return ResourceManager.GetString("HeroCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating new heroes is currently disabled. 的本地化字符串。
        /// </summary>
        internal static string HeroCreationDisabled {
            get {
                return ResourceManager.GetString("HeroCreationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Hero Name is not acceptable. 的本地化字符串。
        /// </summary>
        internal static string HeroNameNotAcceptable {
            get {
                return ResourceManager.GetString("HeroNameNotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HP Drain Rate 的本地化字符串。
        /// </summary>
        internal static string HPDrainRateText {
            get {
                return ResourceManager.GetString("HPDrainRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the required information. 的本地化字符串。
        /// </summary>
        internal static string InputBoxPrompt {
            get {
                return ResourceManager.GetString("InputBoxPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot hold enough gold to get your sale. 的本地化字符串。
        /// </summary>
        internal static string InsufficientGold {
            get {
                return ResourceManager.GetString("InsufficientGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough weight or space spare to buy this item. 的本地化字符串。
        /// </summary>
        internal static string InsufficientWeight {
            get {
                return ResourceManager.GetString("InsufficientWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} isn&apos;t a ring. 的本地化字符串。
        /// </summary>
        internal static string IsntRing {
            get {
                return ResourceManager.GetString("IsntRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has already been sold. 的本地化字符串。
        /// </summary>
        internal static string ItemAlreadySold {
            get {
                return ResourceManager.GetString("ItemAlreadySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}&apos;s dura has dropped to 0. 的本地化字符串。
        /// </summary>
        internal static string ItemDurabilityZero {
            get {
                return ResourceManager.GetString("ItemDurabilityZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has Expired and cannot be brought. 的本地化字符串。
        /// </summary>
        internal static string ItemExpired {
            get {
                return ResourceManager.GetString("ItemExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is no longer loyal to you. 的本地化字符串。
        /// </summary>
        internal static string ItemNoLongerLoyal {
            get {
                return ResourceManager.GetString("ItemNoLongerLoyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item will be Destroyed 的本地化字符串。
        /// </summary>
        internal static string ItemWillBeDestroyed {
            get {
                return ResourceManager.GetString("ItemWillBeDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to join the {0} guild? 的本地化字符串。
        /// </summary>
        internal static string JoinGuildPrompt {
            get {
                return ResourceManager.GetString("JoinGuildPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have left the group. 的本地化字符串。
        /// </summary>
        internal static string LeftGroupMessage {
            get {
                return ResourceManager.GetString("LeftGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loyalty 的本地化字符串。
        /// </summary>
        internal static string LoyaltyText {
            get {
                return ResourceManager.GetString("LoyaltyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAC 的本地化字符串。
        /// </summary>
        internal static string MACText {
            get {
                return ResourceManager.GetString("MACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic Resist 的本地化字符串。
        /// </summary>
        internal static string MagicResistText {
            get {
                return ResourceManager.GetString("MagicResistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mana Recovery 的本地化字符串。
        /// </summary>
        internal static string ManaRecoveryText {
            get {
                return ResourceManager.GetString("ManaRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has asked for your hand in marriage. 的本地化字符串。
        /// </summary>
        internal static string MarriageRequest {
            get {
                return ResourceManager.GetString("MarriageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max AC 的本地化字符串。
        /// </summary>
        internal static string MaxACText {
            get {
                return ResourceManager.GetString("MaxACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max DC 的本地化字符串。
        /// </summary>
        internal static string MaxDCText {
            get {
                return ResourceManager.GetString("MaxDCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max HP 的本地化字符串。
        /// </summary>
        internal static string MaxHPText {
            get {
                return ResourceManager.GetString("MaxHPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Level 的本地化字符串。
        /// </summary>
        internal static string MaximumLevelText {
            get {
                return ResourceManager.GetString("MaximumLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max MAC 的本地化字符串。
        /// </summary>
        internal static string MaxMACText {
            get {
                return ResourceManager.GetString("MaxMACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max MC 的本地化字符串。
        /// </summary>
        internal static string MaxMCText {
            get {
                return ResourceManager.GetString("MaxMCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max MP 的本地化字符串。
        /// </summary>
        internal static string MaxMPText {
            get {
                return ResourceManager.GetString("MaxMPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max SC 的本地化字符串。
        /// </summary>
        internal static string MaxSCText {
            get {
                return ResourceManager.GetString("MaxSCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MC 的本地化字符串。
        /// </summary>
        internal static string MCText {
            get {
                return ResourceManager.GetString("MCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -{0} has left the group. 的本地化字符串。
        /// </summary>
        internal static string MemberLeftGroupMessage {
            get {
                return ResourceManager.GetString("MemberLeftGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has not met the minimum bid yet. 的本地化字符串。
        /// </summary>
        internal static string MinimumBidNotMet {
            get {
                return ResourceManager.GetString("MinimumBidNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No bag space. 的本地化字符串。
        /// </summary>
        internal static string NoBagSpace {
            get {
                return ResourceManager.GetString("NoBagSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot make anymore Heroes. 的本地化字符串。
        /// </summary>
        internal static string NoMoreHeroes {
            get {
                return ResourceManager.GetString("NoMoreHeroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No parcels to collect. 的本地化字符串。
        /// </summary>
        internal static string NoParcelsToCollect {
            get {
                return ResourceManager.GetString("NoParcelsToCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have not supplied enough materials. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughMaterials {
            get {
                return ResourceManager.GetString("NotEnoughMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing Found. 的本地化字符串。
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} donated {1} gold to guild funds. 的本地化字符串。
        /// </summary>
        internal static string PlayerDonatedGold {
            get {
                return ResourceManager.GetString("PlayerDonatedGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -{0} has joined the group. 的本地化字符串。
        /// </summary>
        internal static string PlayerJoinedGroup {
            get {
                return ResourceManager.GetString("PlayerJoinedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} joined guild. 的本地化字符串。
        /// </summary>
        internal static string PlayerJoinedGuild {
            get {
                return ResourceManager.GetString("PlayerJoinedGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} got removed from the guild. 的本地化字符串。
        /// </summary>
        internal static string PlayerKickedFromGuild {
            get {
                return ResourceManager.GetString("PlayerKickedFromGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} left the guild. 的本地化字符串。
        /// </summary>
        internal static string PlayerLeftGuild {
            get {
                return ResourceManager.GetString("PlayerLeftGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} logged on. 的本地化字符串。
        /// </summary>
        internal static string PlayerLoggedOn {
            get {
                return ResourceManager.GetString("PlayerLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} retrieved {1} gold from guild funds. 的本地化字符串。
        /// </summary>
        internal static string PlayerRetrievedGold {
            get {
                return ResourceManager.GetString("PlayerRetrievedGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Poison Recovery 的本地化字符串。
        /// </summary>
        internal static string PoisonRecoveryText {
            get {
                return ResourceManager.GetString("PoisonRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Poison Resist 的本地化字符串。
        /// </summary>
        internal static string PoisonResistText {
            get {
                return ResourceManager.GetString("PoisonResistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Poison 的本地化字符串。
        /// </summary>
        internal static string PoisonText {
            get {
                return ResourceManager.GetString("PoisonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        internal static string PriceText {
            get {
                return ResourceManager.GetString("PriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} would like to share a quest with you. Do you accept? 的本地化字符串。
        /// </summary>
        internal static string QuestShareRequest {
            get {
                return ResourceManager.GetString("QuestShareRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refine 的本地化字符串。
        /// </summary>
        internal static string RefineText {
            get {
                return ResourceManager.GetString("RefineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflect chance 的本地化字符串。
        /// </summary>
        internal static string ReflectChanceText {
            get {
                return ResourceManager.GetString("ReflectChanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair 的本地化字符串。
        /// </summary>
        internal static string RepairText {
            get {
                return ResourceManager.GetString("RepairText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        internal static string ReplaceText {
            get {
                return ResourceManager.GetString("ReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Base AC 的本地化字符串。
        /// </summary>
        internal static string RequiredBaseACText {
            get {
                return ResourceManager.GetString("RequiredBaseACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Base DC 的本地化字符串。
        /// </summary>
        internal static string RequiredBaseDCText {
            get {
                return ResourceManager.GetString("RequiredBaseDCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Base MAC 的本地化字符串。
        /// </summary>
        internal static string RequiredBaseMACText {
            get {
                return ResourceManager.GetString("RequiredBaseMACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Base MC 的本地化字符串。
        /// </summary>
        internal static string RequiredBaseMCText {
            get {
                return ResourceManager.GetString("RequiredBaseMCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Base SC 的本地化字符串。
        /// </summary>
        internal static string RequiredBaseSCText {
            get {
                return ResourceManager.GetString("RequiredBaseSCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required 的本地化字符串。
        /// </summary>
        internal static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string ResetText {
            get {
                return ResourceManager.GetString("ResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to be revived? 的本地化字符串。
        /// </summary>
        internal static string RevivePrompt {
            get {
                return ResourceManager.GetString("RevivePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sale 的本地化字符串。
        /// </summary>
        internal static string SaleText {
            get {
                return ResourceManager.GetString("SaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SC 的本地化字符串。
        /// </summary>
        internal static string SCText {
            get {
                return ResourceManager.GetString("SCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seals for {0} 的本地化字符串。
        /// </summary>
        internal static string SealsForText {
            get {
                return ResourceManager.GetString("SealsForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can search again after {0} seconds. 的本地化字符串。
        /// </summary>
        internal static string SearchAgainAfter {
            get {
                return ResourceManager.GetString("SearchAgainAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selling Price 的本地化字符串。
        /// </summary>
        internal static string SellingPriceText {
            get {
                return ResourceManager.GetString("SellingPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket 的本地化字符串。
        /// </summary>
        internal static string SocketText {
            get {
                return ResourceManager.GetString("SocketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SoulBinds on equip 的本地化字符串。
        /// </summary>
        internal static string SoulBindsOnEquip {
            get {
                return ResourceManager.GetString("SoulBindsOnEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S. Repair 的本地化字符串。
        /// </summary>
        internal static string SRepairText {
            get {
                return ResourceManager.GetString("SRepairText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strong 的本地化字符串。
        /// </summary>
        internal static string StrongText {
            get {
                return ResourceManager.GetString("StrongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must be wearing a suitable weapon to perform this skill 的本地化字符串。
        /// </summary>
        internal static string SuitableWeaponRequired {
            get {
                return ResourceManager.GetString("SuitableWeaponRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target is too far. 的本地化字符串。
        /// </summary>
        internal static string TargetTooFar {
            get {
                return ResourceManager.GetString("TargetTooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (Level {1}) has requested you teach him the ways of the {2}. 的本地化字符串。
        /// </summary>
        internal static string TeachRequest {
            get {
                return ResourceManager.GetString("TeachRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are too far away from the Trust Merchant. 的本地化字符串。
        /// </summary>
        internal static string TooFarFromMerchant {
            get {
                return ResourceManager.GetString("TooFarFromMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Open Sockets 的本地化字符串。
        /// </summary>
        internal static string ToOpenSockets {
            get {
                return ResourceManager.GetString("ToOpenSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has requested to trade with you. 的本地化字符串。
        /// </summary>
        internal static string TradeRequest {
            get {
                return ResourceManager.GetString("TradeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use the TrustMerchant when dead. 的本地化字符串。
        /// </summary>
        internal static string TrustMerchantDead {
            get {
                return ResourceManager.GetString("TrustMerchantDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot buy from the TrustMerchant without using. 的本地化字符串。
        /// </summary>
        internal static string TrustMerchantNoUse {
            get {
                return ResourceManager.GetString("TrustMerchantNoUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Type Required 的本地化字符串。
        /// </summary>
        internal static string UnknownTypeRequired {
            get {
                return ResourceManager.GetString("UnknownTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade Failed. 的本地化字符串。
        /// </summary>
        internal static string UpgradeFailed {
            get {
                return ResourceManager.GetString("UpgradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade Success. 的本地化字符串。
        /// </summary>
        internal static string UpgradeSuccess {
            get {
                return ResourceManager.GetString("UpgradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Cross Half Moon. 的本地化字符串。
        /// </summary>
        internal static string UseCrossHalfMoon {
            get {
                return ResourceManager.GetString("UseCrossHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Double Slash. 的本地化字符串。
        /// </summary>
        internal static string UseDoubleSlash {
            get {
                return ResourceManager.GetString("UseDoubleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Half Moon. 的本地化字符串。
        /// </summary>
        internal static string UseHalfMoon {
            get {
                return ResourceManager.GetString("UseHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The person you were observing has logged off. 的本地化字符串。
        /// </summary>
        internal static string UserLoggedOff {
            get {
                return ResourceManager.GetString("UserLoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Thrusting. 的本地化字符串。
        /// </summary>
        internal static string UseThrusting {
            get {
                return ResourceManager.GetString("UseThrusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wear Weight 的本地化字符串。
        /// </summary>
        internal static string WearWeightText {
            get {
                return ResourceManager.GetString("WearWeightText", resourceCulture);
            }
        }
    }
}
