//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Library {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerLibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerLibraryResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Library.ServerLibraryResources", typeof(ServerLibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now allowing marriage requests. 的本地化字符串。
        /// </summary>
        internal static string AllowMarriageRequests {
            get {
                return ResourceManager.GetString("AllowMarriageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now allowing recall from lover. 的本地化字符串。
        /// </summary>
        internal static string AllowRecallFromLover {
            get {
                return ResourceManager.GetString("AllowRecallFromLover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already part of a guild. 的本地化字符串。
        /// </summary>
        internal static string AlreadyPartOfGuild {
            get {
                return ResourceManager.GetString("AlreadyPartOfGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re already refining an item. 的本地化字符串。
        /// </summary>
        internal static string AlreadyRefiningItem {
            get {
                return ResourceManager.GetString("AlreadyRefiningItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can already unequip a cursed item. 的本地化字符串。
        /// </summary>
        internal static string AlreadyUnequipCursedItem {
            get {
                return ResourceManager.GetString("AlreadyUnequipCursedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archers cannot use this item. 的本地化字符串。
        /// </summary>
        internal static string ArchersCannotUse {
            get {
                return ResourceManager.GetString("ArchersCannotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archers repaired: {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string ArchersRepaired {
            get {
                return ResourceManager.GetString("ArchersRepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assassins cannot use this item. 的本地化字符串。
        /// </summary>
        internal static string AssassinsCannotUse {
            get {
                return ResourceManager.GetString("AssassinsCannotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have to be at least level {0} to create a guild. 的本地化字符串。
        /// </summary>
        internal static string AtLeastLevelCreateGuild {
            get {
                return ResourceManager.GetString("AtLeastLevelCreateGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have to be at least level {0} to create a hero. 的本地化字符串。
        /// </summary>
        internal static string AtLeastLevelCreateHero {
            get {
                return ResourceManager.GetString("AtLeastLevelCreateHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is attempting to revive {1} 的本地化字符串。
        /// </summary>
        internal static string AttemptToRevive {
            get {
                return ResourceManager.GetString("AttemptToRevive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auction both sold and Expired {0} 的本地化字符串。
        /// </summary>
        internal static string AuctionSoldExpired {
            get {
                return ResourceManager.GetString("AuctionSoldExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now blocking marriage requests. 的本地化字符串。
        /// </summary>
        internal static string BlockMarriageRequests {
            get {
                return ResourceManager.GetString("BlockMarriageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now blocking recall from lover. 的本地化字符串。
        /// </summary>
        internal static string BlockRecallFromLover {
            get {
                return ResourceManager.GetString("BlockRecallFromLover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You bought {0} for {1:#,##0} Gold 的本地化字符串。
        /// </summary>
        internal static string BoughtForGold {
            get {
                return ResourceManager.GetString("BoughtForGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Buffs Loaded. 的本地化字符串。
        /// </summary>
        internal static string BuffsLoaded {
            get {
                return ResourceManager.GetString("BuffsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot carry anymore. 的本地化字符串。
        /// </summary>
        internal static string CannotCarryAnymore {
            get {
                return ResourceManager.GetString("CannotCarryAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot load a database version {0}. Maximum supported is {1}. 的本地化字符串。
        /// </summary>
        internal static string CannotLoadDatabaseMaxVersion {
            get {
                return ResourceManager.GetString("CannotLoadDatabaseMaxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot load a database version {0}. Minimum supported is {1}. 的本地化字符串。
        /// </summary>
        internal static string CannotLoadDatabaseMinVersion {
            get {
                return ResourceManager.GetString("CannotLoadDatabaseMinVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot message player whilst they are on your blacklist. 的本地化字符串。
        /// </summary>
        internal static string CannotMesBlacklist {
            get {
                return ResourceManager.GetString("CannotMesBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot recall for another {0} seconds 的本地化字符串。
        /// </summary>
        internal static string CannotRecallAnotherSeconds {
            get {
                return ResourceManager.GetString("CannotRecallAnotherSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot recall people on this map 的本地化字符串。
        /// </summary>
        internal static string CannotRecallThisMap {
            get {
                return ResourceManager.GetString("CannotRecallThisMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot recall when you are dead. 的本地化字符串。
        /// </summary>
        internal static string CannotRecallWhenDead {
            get {
                return ResourceManager.GetString("CannotRecallWhenDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot ride here without a bridle 的本地化字符串。
        /// </summary>
        internal static string CannotRideHereWithoutBridle {
            get {
                return ResourceManager.GetString("CannotRideHereWithoutBridle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot ride on this map 的本地化字符串。
        /// </summary>
        internal static string CannotRideThisMap {
            get {
                return ResourceManager.GetString("CannotRideThisMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot teleport on this map 的本地化字符串。
        /// </summary>
        internal static string CannotTeleportThisMap {
            get {
                return ResourceManager.GetString("CannotTeleportThisMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot use on this map 的本地化字符串。
        /// </summary>
        internal static string CannotUseOnMap {
            get {
                return ResourceManager.GetString("CannotUseOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use Potions here 的本地化字符串。
        /// </summary>
        internal static string CannotUsePotionsHere {
            get {
                return ResourceManager.GetString("CannotUsePotionsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only be used with a creature summoned 的本地化字符串。
        /// </summary>
        internal static string CanOnlyUsedWithCreatureSummoned {
            get {
                return ResourceManager.GetString("CanOnlyUsedWithCreatureSummoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only be used with a fishing rod 的本地化字符串。
        /// </summary>
        internal static string CanOnlyUsedWithFishingRod {
            get {
                return ResourceManager.GetString("CanOnlyUsedWithFishingRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only be used with a mount 的本地化字符串。
        /// </summary>
        internal static string CanOnlyUsedWithMount {
            get {
                return ResourceManager.GetString("CanOnlyUsedWithMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has captured {1} at {2} 的本地化字符串。
        /// </summary>
        internal static string CapturedAt {
            get {
                return ResourceManager.GetString("CapturedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has captured the hill 的本地化字符串。
        /// </summary>
        internal static string CapturedHill {
            get {
                return ResourceManager.GetString("CapturedHill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, {1}, Client version matched. 的本地化字符串。
        /// </summary>
        internal static string ClientVersionMatched {
            get {
                return ResourceManager.GetString("ClientVersionMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, Connected. 的本地化字符串。
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conquest: {0} 的本地化字符串。
        /// </summary>
        internal static string ConquestInfoName {
            get {
                return ResourceManager.GetString("ConquestInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Owner: {0} 的本地化字符串。
        /// </summary>
        internal static string ConquestOwner {
            get {
                return ResourceManager.GetString("ConquestOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find {0}. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFind {
            get {
                return ResourceManager.GetString("CouldNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find Ingredient: {0}, Recipe: {1} 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindIngredient {
            get {
                return ResourceManager.GetString("CouldNotFindIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find ingredients: {0}, File: {1} 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindIngredients {
            get {
                return ResourceManager.GetString("CouldNotFindIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find Item: {0} 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindItem1 {
            get {
                return ResourceManager.GetString("CouldNotFindItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find Item: {0}, File: {1} 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindItem2 {
            get {
                return ResourceManager.GetString("CouldNotFindItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find recipe: {0}, File: {1} 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindRecipe {
            get {
                return ResourceManager.GetString("CouldNotFindRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find Tool: {0}, Recipe: {1} 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindTool {
            get {
                return ResourceManager.GetString("CouldNotFindTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not level player 的本地化字符串。
        /// </summary>
        internal static string CouldNotLevelPlayer {
            get {
                return ResourceManager.GetString("CouldNotLevelPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not load Drop: {0}, Line {1} 的本地化字符串。
        /// </summary>
        internal static string CouldNotLoadDrop {
            get {
                return ResourceManager.GetString("CouldNotLoadDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not parse option: {0}, Value: {1} 的本地化字符串。
        /// </summary>
        internal static string CouldNotParseOption {
            get {
                return ResourceManager.GetString("CouldNotParseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crafting attempt failed. 的本地化字符串。
        /// </summary>
        internal static string CraftingAttemptFailed {
            get {
                return ResourceManager.GetString("CraftingAttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have disbanded the guild 的本地化字符串。
        /// </summary>
        internal static string DisbandedGuild {
            get {
                return ResourceManager.GetString("DisbandedGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Disconnected, Invalid packet. 的本地化字符串。
        /// </summary>
        internal static string DisconnectedInvalidPacket {
            get {
                return ResourceManager.GetString("DisconnectedInvalidPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Disconnected, Large amount of Packets. LastPackets: {1}. 的本地化字符串。
        /// </summary>
        internal static string DisconnectedLargePackets {
            get {
                return ResourceManager.GetString("DisconnectedLargePackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, Disconnected - Wrong Client Version. 的本地化字符串。
        /// </summary>
        internal static string DisconnectedWrongClientVersion {
            get {
                return ResourceManager.GetString("DisconnectedWrongClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 does not need to be vitalized 的本地化字符串。
        /// </summary>
        internal static string DoesNotNeedVitalized {
            get {
                return ResourceManager.GetString("DoesNotNeedVitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough AC. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveEnoughAC {
            get {
                return ResourceManager.GetString("DoNotHaveEnoughAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough Base AC. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveEnoughBaseAC {
            get {
                return ResourceManager.GetString("DoNotHaveEnoughBaseAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough Base DC. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveEnoughBaseDC {
            get {
                return ResourceManager.GetString("DoNotHaveEnoughBaseDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough Base MAC. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveEnoughBaseMAC {
            get {
                return ResourceManager.GetString("DoNotHaveEnoughBaseMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough Base MC. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveEnoughBaseMC {
            get {
                return ResourceManager.GetString("DoNotHaveEnoughBaseMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough Base SC. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveEnoughBaseSC {
            get {
                return ResourceManager.GetString("DoNotHaveEnoughBaseSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough MAC. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveEnoughMAC {
            get {
                return ResourceManager.GetString("DoNotHaveEnoughMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have a mount equiped. 的本地化字符串。
        /// </summary>
        internal static string DoNotHaveMountEquiped {
            get {
                return ResourceManager.GetString("DoNotHaveMountEquiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dragon Loaded. 的本地化字符串。
        /// </summary>
        internal static string DragonLoaded {
            get {
                return ResourceManager.GetString("DragonLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drops Loaded. 的本地化字符串。
        /// </summary>
        internal static string DropsLoaded {
            get {
                return ResourceManager.GetString("DropsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Envir Started. 的本地化字符串。
        /// </summary>
        internal static string EnvirStarted {
            get {
                return ResourceManager.GetString("EnvirStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Envir Stopped. 的本地化字符串。
        /// </summary>
        internal static string EnvirStopped {
            get {
                return ResourceManager.GetString("EnvirStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have exceeded the maximum level. 的本地化字符串。
        /// </summary>
        internal static string ExceededMaximumLevel {
            get {
                return ResourceManager.GetString("ExceededMaximumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expanded storage has expired. 的本地化字符串。
        /// </summary>
        internal static string ExpandedStorageExpired {
            get {
                return ResourceManager.GetString("ExpandedStorageExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create UserItem: {0}, Page: {1} 的本地化字符串。
        /// </summary>
        internal static string FailedToCreateUserItem {
            get {
                return ResourceManager.GetString("FailedToCreateUserItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get ItemInfo: {0}, Page: {1} 的本地化字符串。
        /// </summary>
        internal static string FailedToGetItemInfo {
            get {
                return ResourceManager.GetString("FailedToGetItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load Dragon 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadDragon {
            get {
                return ResourceManager.GetString("FailedToLoadDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load Dragon (bad map name): {0} 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadDragonMapName {
            get {
                return ResourceManager.GetString("FailedToLoadDragonMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load Dragon (bad map XY): {0} 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadDragonMapXY {
            get {
                return ResourceManager.GetString("FailedToLoadDragonMapXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load Dragon (bad monster name): {0} 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadDragonMonster {
            get {
                return ResourceManager.GetString("FailedToLoadDragonMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to Load Map: {0} 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadMap {
            get {
                return ResourceManager.GetString("FailedToLoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Not Found: {0}, Quest: {1} 的本地化字符串。
        /// </summary>
        internal static string FileNotFoundQuest {
            get {
                return ResourceManager.GetString("FileNotFoundQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game is currently in test mode. 的本地化字符串。
        /// </summary>
        internal static string GameCurTest {
            get {
                return ResourceManager.GetString("GameCurTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gameshop Purchase Logs Cleared. 的本地化字符串。
        /// </summary>
        internal static string GameshopPurchaseLogsCleared {
            get {
                return ResourceManager.GetString("GameshopPurchaseLogsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gates repaired: {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string GatesRepaired {
            get {
                return ResourceManager.GetString("GatesRepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} had gender change to {1} by GM: {2} 的本地化字符串。
        /// </summary>
        internal static string GenderChangeByGM {
            get {
                return ResourceManager.GetString("GenderChangeByGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} attempted a GM login 的本地化字符串。
        /// </summary>
        internal static string GMAttempt {
            get {
                return ResourceManager.GetString("GMAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @CONQUESTREPAIRALL invoked by GM: {0} on account index: {1} 的本地化字符串。
        /// </summary>
        internal static string GMConquestRepairAll {
            get {
                return ResourceManager.GetString("GMConquestRepairAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A guild leader needs to be at least level {0} 的本地化字符串。
        /// </summary>
        internal static string GuildLeaderNeedsLevel {
            get {
                return ResourceManager.GetString("GuildLeaderNeedsLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A guild needs at least 2 leaders. 的本地化字符串。
        /// </summary>
        internal static string GuildNeeds2Leaders {
            get {
                return ResourceManager.GetString("GuildNeeds2Leaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild 的本地化字符串。
        /// </summary>
        internal static string GuildText {
            get {
                return ResourceManager.GetString("GuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} guild will be deleted from the server. 的本地化字符串。
        /// </summary>
        internal static string GuildWillBeDeleted {
            get {
                return ResourceManager.GetString("GuildWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has been created. 的本地化字符串。
        /// </summary>
        internal static string HasBeenCreated {
            get {
                return ResourceManager.GetString("HasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has dropped {1}. 的本地化字符串。
        /// </summary>
        internal static string HasDropped {
            get {
                return ResourceManager.GetString("HasDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero Inventory is already at Maximum 的本地化字符串。
        /// </summary>
        internal static string HeroInventoryAlreadyMaximum {
            get {
                return ResourceManager.GetString("HeroInventoryAlreadyMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero Inventory Increased 的本地化字符串。
        /// </summary>
        internal static string HeroInventoryIncreased {
            get {
                return ResourceManager.GetString("HeroInventoryIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero has been given a second chance at life 的本地化字符串。
        /// </summary>
        internal static string HeroSecondChanceLife {
            get {
                return ResourceManager.GetString("HeroSecondChanceLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero&apos;s weapon has been completely repaired 的本地化字符串。
        /// </summary>
        internal static string HeroWeaponCompletelyRepaired {
            get {
                return ResourceManager.GetString("HeroWeaponCompletelyRepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero&apos;s weapon has been partially repaired 的本地化字符串。
        /// </summary>
        internal static string HeroWeaponPartiallyRepaired {
            get {
                return ResourceManager.GetString("HeroWeaponPartiallyRepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HttpService started. 的本地化字符串。
        /// </summary>
        internal static string HttpServiceStarted {
            get {
                return ResourceManager.GetString("HttpServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HttpService start failed! Error: {0} 的本地化字符串。
        /// </summary>
        internal static string HttpServiceStartFailed {
            get {
                return ResourceManager.GetString("HttpServiceStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INCLUDE Script Not Found: {0} 的本地化字符串。
        /// </summary>
        internal static string IncludeScriptNotFound {
            get {
                return ResourceManager.GetString("IncludeScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect login password 的本地化字符串。
        /// </summary>
        internal static string IncorrectLoginPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect operator: {0}, Page: {1} 的本地化字符串。
        /// </summary>
        internal static string IncorrectOperator {
            get {
                return ResourceManager.GetString("IncorrectOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT Script Not Found: {0} 的本地化字符串。
        /// </summary>
        internal static string InsertScriptNotFound {
            get {
                return ResourceManager.GetString("InsertScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid packet received. Index: {0} 的本地化字符串。
        /// </summary>
        internal static string InvalidPacketReceived {
            get {
                return ResourceManager.GetString("InvalidPacketReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is blocking grouprecall 的本地化字符串。
        /// </summary>
        internal static string IsBlockingGrouprecall {
            get {
                return ResourceManager.GetString("IsBlockingGrouprecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is not hungry 的本地化字符串。
        /// </summary>
        internal static string IsNotHungry {
            get {
                return ResourceManager.GetString("IsNotHungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} isn&apos;t online. 的本地化字符串。
        /// </summary>
        internal static string IsntOnline {
            get {
                return ResourceManager.GetString("IsntOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has just expired from your inventory. 的本地化字符串。
        /// </summary>
        internal static string JustExpiredFromYourInventory {
            get {
                return ResourceManager.GetString("JustExpiredFromYourInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} was totally killed by GM: {1} 的本地化字符串。
        /// </summary>
        internal static string KilledByGM {
            get {
                return ResourceManager.GetString("KilledByGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LineMessages reloaded. 的本地化字符串。
        /// </summary>
        internal static string LineMessagesReloaded {
            get {
                return ResourceManager.GetString("LineMessagesReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Account has been Banned! 的本地化字符串。
        /// </summary>
        internal static string LoggedOutAccountBanned {
            get {
                return ResourceManager.GetString("LoggedOutAccountBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Began observing 的本地化字符串。
        /// </summary>
        internal static string LoggedOutBeganObserving {
            get {
                return ResourceManager.GetString("LoggedOutBeganObserving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Chat message too long 的本地化字符串。
        /// </summary>
        internal static string LoggedOutChatMesLong {
            get {
                return ResourceManager.GetString("LoggedOutChatMesLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Connection timed out 的本地化字符串。
        /// </summary>
        internal static string LoggedOutConnectTimeOut {
            get {
                return ResourceManager.GetString("LoggedOutConnectTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Double login 的本地化字符串。
        /// </summary>
        internal static string LoggedOutDoubleLogin {
            get {
                return ResourceManager.GetString("LoggedOutDoubleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Kicked by admin 的本地化字符串。
        /// </summary>
        internal static string LoggedOutKickedByAdmin {
            get {
                return ResourceManager.GetString("LoggedOutKickedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Maximum connections reached 的本地化字符串。
        /// </summary>
        internal static string LoggedOutMaxConnect {
            get {
                return ResourceManager.GetString("LoggedOutMaxConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Server closed 的本地化字符串。
        /// </summary>
        internal static string LoggedOutServerClosed {
            get {
                return ResourceManager.GetString("LoggedOutServerClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Server crashed 的本地化字符串。
        /// </summary>
        internal static string LoggedOutServerCrashed {
            get {
                return ResourceManager.GetString("LoggedOutServerCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: User closed game 的本地化字符串。
        /// </summary>
        internal static string LoggedOutUserClose {
            get {
                return ResourceManager.GetString("LoggedOutUserClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: User gone missing / disconnected 的本地化字符串。
        /// </summary>
        internal static string LoggedOutUserDisConnect {
            get {
                return ResourceManager.GetString("LoggedOutUserDisConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: User returned to select char 的本地化字符串。
        /// </summary>
        internal static string LoggedOutUserSelectChar {
            get {
                return ResourceManager.GetString("LoggedOutUserSelectChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Wrong client version 的本地化字符串。
        /// </summary>
        internal static string LoggedOutWrongClientVers {
            get {
                return ResourceManager.GetString("LoggedOutWrongClientVers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Has logged out. Reason: Unknown 的本地化字符串。
        /// </summary>
        internal static string LoggeedOutUnknown {
            get {
                return ResourceManager.GetString("LoggeedOutUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your mailbox is overflowing. 的本地化字符串。
        /// </summary>
        internal static string MailboxOverflowing {
            get {
                return ResourceManager.GetString("MailboxOverflowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename: {0} 的本地化字符串。
        /// </summary>
        internal static string MapFileName {
            get {
                return ResourceManager.GetString("MapFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Maps Loaded. 的本地化字符串。
        /// </summary>
        internal static string MapsLoaded {
            get {
                return ResourceManager.GetString("MapsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must be the leader to request a war. 的本地化字符串。
        /// </summary>
        internal static string MustLeaderToRequestWar {
            get {
                return ResourceManager.GetString("MustLeaderToRequestWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need at least 1 leader online. 的本地化字符串。
        /// </summary>
        internal static string Need1LeaderOnline {
            get {
                return ResourceManager.GetString("Need1LeaderOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be the last leading member of the guild to disband the guild. 的本地化字符串。
        /// </summary>
        internal static string NeedLastLeadingToDisband {
            get {
                return ResourceManager.GetString("NeedLastLeadingToDisband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Started. 的本地化字符串。
        /// </summary>
        internal static string NetworkStarted {
            get {
                return ResourceManager.GetString("NetworkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Stopped. 的本地化字符串。
        /// </summary>
        internal static string NetworkStopped {
            get {
                return ResourceManager.GetString("NetworkStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, {1}, New account being created. 的本地化字符串。
        /// </summary>
        internal static string NewAccountBeingCreated {
            get {
                return ResourceManager.GetString("NewAccountBeingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Amulet 的本地化字符串。
        /// </summary>
        internal static string NoAmulet {
            get {
                return ResourceManager.GetString("NoAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Armour 的本地化字符串。
        /// </summary>
        internal static string NoArmour {
            get {
                return ResourceManager.GetString("NoArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Belt 的本地化字符串。
        /// </summary>
        internal static string NoBelt {
            get {
                return ResourceManager.GetString("NoBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Boots 的本地化字符串。
        /// </summary>
        internal static string NoBoots {
            get {
                return ResourceManager.GetString("NoBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Bracelet 的本地化字符串。
        /// </summary>
        internal static string NoBracelet {
            get {
                return ResourceManager.GetString("NoBracelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No current owner. 的本地化字符串。
        /// </summary>
        internal static string NoCurrentOwner {
            get {
                return ResourceManager.GetString("NoCurrentOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Guild 的本地化字符串。
        /// </summary>
        internal static string NoGuild {
            get {
                return ResourceManager.GetString("NoGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Helmet 的本地化字符串。
        /// </summary>
        internal static string NoHelmet {
            get {
                return ResourceManager.GetString("NoHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Necklace 的本地化字符串。
        /// </summary>
        internal static string NoNecklace {
            get {
                return ResourceManager.GetString("NoNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GM Command @CONQUESTREPAIRALL invoked by non-GM player: {0} 的本地化字符串。
        /// </summary>
        internal static string NonGMPlayerConquestRepairAll {
            get {
                return ResourceManager.GetString("NonGMPlayerConquestRepairAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No pushing in the safezone. tut tut. 的本地化字符串。
        /// </summary>
        internal static string NoPushingInTheSafezone {
            get {
                return ResourceManager.GetString("NoPushingInTheSafezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Ring 的本地化字符串。
        /// </summary>
        internal static string NoRing {
            get {
                return ResourceManager.GetString("NoRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Stone 的本地化字符串。
        /// </summary>
        internal static string NoStone {
            get {
                return ResourceManager.GetString("NoStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough jumping power. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughJumpingPower {
            get {
                return ResourceManager.GetString("NotEnoughJumpingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough pushing Power. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughPushingPower {
            get {
                return ResourceManager.GetString("NotEnoughPushingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing was found. 的本地化字符串。
        /// </summary>
        internal static string NothingWasFound {
            get {
                return ResourceManager.GetString("NothingWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Torch 的本地化字符串。
        /// </summary>
        internal static string NoTorch {
            get {
                return ResourceManager.GetString("NoTorch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Weapon 的本地化字符串。
        /// </summary>
        internal static string NoWeapon {
            get {
                return ResourceManager.GetString("NoWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can now unequip a cursed item. 的本地化字符串。
        /// </summary>
        internal static string NowUnequipCursedItem {
            get {
                return ResourceManager.GetString("NowUnequipCursedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NPC Scripts reloaded... 的本地化字符串。
        /// </summary>
        internal static string NPCScriptsReloaded {
            get {
                return ResourceManager.GetString("NPCScriptsReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, {1}, Password being changed. 的本地化字符串。
        /// </summary>
        internal static string PasswordBeingChanged {
            get {
                return ResourceManager.GetString("PasswordBeingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been archived by {1} 的本地化字符串。
        /// </summary>
        internal static string PlayerArchived {
            get {
                return ResourceManager.GetString("PlayerArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been archived due to {1} month deletion. 的本地化字符串。
        /// </summary>
        internal static string PlayerArchivedDue1 {
            get {
                return ResourceManager.GetString("PlayerArchivedDue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been archived due to no login after {1} months. 的本地化字符串。
        /// </summary>
        internal static string PlayerArchivedDue2 {
            get {
                return ResourceManager.GetString("PlayerArchivedDue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been archived due to {1} months inactivity. 的本地化字符串。
        /// </summary>
        internal static string PlayerArchivedDue3 {
            get {
                return ResourceManager.GetString("PlayerArchivedDue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been backed up by {1} 的本地化字符串。
        /// </summary>
        internal static string PlayerBackedUp {
            get {
                return ResourceManager.GetString("PlayerBackedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been changed to {1} 的本地化字符串。
        /// </summary>
        internal static string PlayerBeenChangedTo {
            get {
                return ResourceManager.GetString("PlayerBeenChangedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been changed to {1} by {2} 的本地化字符串。
        /// </summary>
        internal static string PlayerChangedClass {
            get {
                return ResourceManager.GetString("PlayerChangedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been changed to {1} by {2} 的本地化字符串。
        /// </summary>
        internal static string PlayerChangedGender {
            get {
                return ResourceManager.GetString("PlayerChangedGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} could not be found 的本地化字符串。
        /// </summary>
        internal static string PlayerCouldNotBeFound {
            get {
                return ResourceManager.GetString("PlayerCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has attempted to Create {1} x{2} 的本地化字符串。
        /// </summary>
        internal static string PlayerCreateAttempt {
            get {
                return ResourceManager.GetString("PlayerCreateAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been given {1} credit 的本地化字符串。
        /// </summary>
        internal static string PlayerGivenCredit {
            get {
                return ResourceManager.GetString("PlayerGivenCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been Levelled {1} -&gt; {2}. 的本地化字符串。
        /// </summary>
        internal static string PlayerHasBeenLevelled {
            get {
                return ResourceManager.GetString("PlayerHasBeenLevelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been Levelled: {1} -&gt; {2} by GM: {3} 的本地化字符串。
        /// </summary>
        internal static string PlayerHasBeenLevelledByGM {
            get {
                return ResourceManager.GetString("PlayerHasBeenLevelledByGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0}&apos;s hero has been Levelled {1} -&gt; {2} by {3} 的本地化字符串。
        /// </summary>
        internal static string PlayerHeroLevelChanged {
            get {
                return ResourceManager.GetString("PlayerHeroLevelChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0}&apos;s hero has been Leveled {1} -&gt; {2} by {3} 的本地化字符串。
        /// </summary>
        internal static string PlayerHeroLevelChangedCurrent {
            get {
                return ResourceManager.GetString("PlayerHeroLevelChangedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0}&apos;s hero has been Levelled {1} -&gt; {2}. 的本地化字符串。
        /// </summary>
        internal static string PlayerHeroLevelled {
            get {
                return ResourceManager.GetString("PlayerHeroLevelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is now a GM 的本地化字符串。
        /// </summary>
        internal static string PlayerIsNowAGM {
            get {
                return ResourceManager.GetString("PlayerIsNowAGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been Levelled {1} -&gt; {2} by {3} 的本地化字符串。
        /// </summary>
        internal static string PlayerLevelChanged {
            get {
                return ResourceManager.GetString("PlayerLevelChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been Leveled {1} -&gt; {2} by {3} 的本地化字符串。
        /// </summary>
        internal static string PlayerLevelChangedCurrent {
            get {
                return ResourceManager.GetString("PlayerLevelChangedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been loaded by {1} 的本地化字符串。
        /// </summary>
        internal static string PlayerLoaded {
            get {
                return ResourceManager.GetString("PlayerLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player is not accepting your messages. 的本地化字符串。
        /// </summary>
        internal static string PlayerNotAcceptYourMes {
            get {
                return ResourceManager.GetString("PlayerNotAcceptYourMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player: {0} was prevented access to NPC key: &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string PlayerPreventedAccess {
            get {
                return ResourceManager.GetString("PlayerPreventedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has been restored by {1} 的本地化字符串。
        /// </summary>
        internal static string PlayerRestored {
            get {
                return ResourceManager.GetString("PlayerRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please type the GM Password 的本地化字符串。
        /// </summary>
        internal static string PleaseTypeGMPassword {
            get {
                return ResourceManager.GetString("PleaseTypeGMPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the randomTextFile: {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string RandomTextFileNotExist {
            get {
                return ResourceManager.GetString("RandomTextFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A recall was attempted without your permission 的本地化字符串。
        /// </summary>
        internal static string RecallAttemptedWithoutYourPermission {
            get {
                return ResourceManager.GetString("RecallAttemptedWithoutYourPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Recipes Loaded. 的本地化字符串。
        /// </summary>
        internal static string RecipesLoaded {
            get {
                return ResourceManager.GetString("RecipesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Not Found: {0} 的本地化字符串。
        /// </summary>
        internal static string ScriptNotFound {
            get {
                return ResourceManager.GetString("ScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server rebooting... 的本地化字符串。
        /// </summary>
        internal static string ServerRebooting {
            get {
                return ResourceManager.GetString("ServerRebooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} shattered upon death. 的本地化字符串。
        /// </summary>
        internal static string ShatteredUponDeath {
            get {
                return ResourceManager.GetString("ShatteredUponDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sieges repaired: {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string SiegesRepaired {
            get {
                return ResourceManager.GetString("SiegesRepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill requires meditation. 的本地化字符串。
        /// </summary>
        internal static string SkillRequiresMeditation {
            get {
                return ResourceManager.GetString("SkillRequiresMeditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You sold {0} for {1:#,##0} Gold 的本地化字符串。
        /// </summary>
        internal static string SoldForGold {
            get {
                return ResourceManager.GetString("SoldForGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taoists cannot use this item. 的本地化字符串。
        /// </summary>
        internal static string TaoistsCannotUse {
            get {
                return ResourceManager.GetString("TaoistsCannotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [threadloop error] {0} 的本地化字符串。
        /// </summary>
        internal static string ThreadloopError {
            get {
                return ResourceManager.GetString("ThreadloopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Disconnected, Too many connections. 的本地化字符串。
        /// </summary>
        internal static string TooManyConnections {
            get {
                return ResourceManager.GetString("TooManyConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has connected. 的本地化字符串。
        /// </summary>
        internal static string UserConnected {
            get {
                return ResourceManager.GetString("UserConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, {1}, User logged in. 的本地化字符串。
        /// </summary>
        internal static string UserLoggedIn {
            get {
                return ResourceManager.GetString("UserLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, {1}, User logging in. 的本地化字符串。
        /// </summary>
        internal static string UserLoggingIn {
            get {
                return ResourceManager.GetString("UserLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Walls repaired: {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string WallsRepaired {
            get {
                return ResourceManager.GetString("WallsRepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warriors cannot use this item. 的本地化字符串。
        /// </summary>
        internal static string WarriorsCannotUse {
            get {
                return ResourceManager.GetString("WarriorsCannotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} War Started. 的本地化字符串。
        /// </summary>
        internal static string WarStarted {
            get {
                return ResourceManager.GetString("WarStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} War Stopped. 的本地化字符串。
        /// </summary>
        internal static string WarStopped {
            get {
                return ResourceManager.GetString("WarStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wizards cannot use this item. 的本地化字符串。
        /// </summary>
        internal static string WizardsCannotUse {
            get {
                return ResourceManager.GetString("WizardsCannotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You won {0} for {1:#,##0} Gold. 的本地化字符串。
        /// </summary>
        internal static string WonForGold {
            get {
                return ResourceManager.GetString("WonForGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [inner workloop error. Line {0}] {1} 的本地化字符串。
        /// </summary>
        internal static string WorkloopError_Inner {
            get {
                return ResourceManager.GetString("WorkloopError_Inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [outer workloop error. Line {0}] {1} 的本地化字符串。
        /// </summary>
        internal static string WorkloopError_Outer {
            get {
                return ResourceManager.GetString("WorkloopError_Outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not a GM and this command is not enabled for you. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotGM1 {
            get {
                return ResourceManager.GetString("YouAreNotGM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not a group leader. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotGroupLeader {
            get {
                return ResourceManager.GetString("YouAreNotGroupLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are a walking explosive. 的本地化字符串。
        /// </summary>
        internal static string YouAreWalkingExplosive {
            get {
                return ResourceManager.GetString("YouAreWalkingExplosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot shout for another {0} seconds. 的本地化字符串。
        /// </summary>
        internal static string YouCannotShoutSeconds {
            get {
                return ResourceManager.GetString("YouCannotShoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been banned from chatting for 5 minutes. 的本地化字符串。
        /// </summary>
        internal static string YouChatBanned5Min {
            get {
                return ResourceManager.GetString("YouChatBanned5Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are currently banned from chatting. 的本地化字符串。
        /// </summary>
        internal static string YouCurChatBanned {
            get {
                return ResourceManager.GetString("YouCurChatBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You died and {0} has been returned to it&apos;s owner. 的本地化字符串。
        /// </summary>
        internal static string YouDiedAndReturn {
            get {
                return ResourceManager.GetString("YouDiedAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been given a second chance at life 的本地化字符串。
        /// </summary>
        internal static string YouGetSecondLife {
            get {
                return ResourceManager.GetString("YouGetSecondLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been murdered by {0} 的本地化字符串。
        /// </summary>
        internal static string YouHaveBeenMurderedBy {
            get {
                return ResourceManager.GetString("YouHaveBeenMurderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have murdered {0} 的本地化字符串。
        /// </summary>
        internal static string YouHaveMurdered {
            get {
                return ResourceManager.GetString("YouHaveMurdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be level 8 before you can shout. 的本地化字符串。
        /// </summary>
        internal static string YouLevel8Shout {
            get {
                return ResourceManager.GetString("YouLevel8Shout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been made a GM 的本地化字符串。
        /// </summary>
        internal static string YouMadeGM {
            get {
                return ResourceManager.GetString("YouMadeGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must have a saddle to ride your mount 的本地化字符串。
        /// </summary>
        internal static string YouMustHaveSaddleToRide {
            get {
                return ResourceManager.GetString("YouMustHaveSaddleToRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be wearing a Wedding Ring for recall. 的本地化字符串。
        /// </summary>
        internal static string YouNeedWeddingRingRecall {
            get {
                return ResourceManager.GetString("YouNeedWeddingRingRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re not married. 的本地化字符串。
        /// </summary>
        internal static string YouNotMarried {
            get {
                return ResourceManager.GetString("YouNotMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;ve been protected by the law 的本地化字符串。
        /// </summary>
        internal static string YouProtectedByLaw {
            get {
                return ResourceManager.GetString("YouProtectedByLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been removed from the guild. 的本地化字符串。
        /// </summary>
        internal static string YourBeenRemoveFromGuild {
            get {
                return ResourceManager.GetString("YourBeenRemoveFromGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your weapon has been cursed. 的本地化字符串。
        /// </summary>
        internal static string YourWeaponCursed {
            get {
                return ResourceManager.GetString("YourWeaponCursed", resourceCulture);
            }
        }
    }
}
