//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AC + {0}~{1} (+{2}) 的本地化字符串。
        /// </summary>
        internal static string AC {
            get {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AC + {0}~{1} 的本地化字符串。
        /// </summary>
        internal static string AC2 {
            get {
                return ResourceManager.GetString("AC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy: + {0} (+{1}) 的本地化字符串。
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy: + {0} 的本地化字符串。
        /// </summary>
        internal static string Accuracy2 {
            get {
                return ResourceManager.GetString("Accuracy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Mentor 的本地化字符串。
        /// </summary>
        internal static string AddMentor {
            get {
                return ResourceManager.GetString("AddMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agility: + {0} (+{1}) 的本地化字符串。
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agility: + {0} 的本地化字符串。
        /// </summary>
        internal static string Agility2 {
            get {
                return ResourceManager.GetString("Agility2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now allowing mentor requests. 的本地化字符串。
        /// </summary>
        internal static string AllowingMentorRequests {
            get {
                return ResourceManager.GetString("AllowingMentorRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archers are a class of great accuracy and strength, using their powerful skills with bows to deal extraordinary damage from range. Much like wizards, they rely on their keen instincts to dodge oncoming attacks as they tend to leave themselves open to frontal attacks. However, their physical prowess and deadly aim allows them to instil fear into anyone they hit. 的本地化字符串。
        /// </summary>
        internal static string ArcherDes {
            get {
                return ResourceManager.GetString("ArcherDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assassins are members of a secret organization and their history is relatively unknown. They&apos;re capable of hiding themselves and performing attacks while being unseen by others, which naturally makes them excellent at making fast kills. It is necessary for them to avoid being in battles with multiple enemies due to their weak vitality and strength. 的本地化字符串。
        /// </summary>
        internal static string AssassinDes {
            get {
                return ResourceManager.GetString("AssassinDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Mode: Attack All] 的本地化字符串。
        /// </summary>
        internal static string AttackMode_All {
            get {
                return ResourceManager.GetString("AttackMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Mode: Enemy Guild] 的本地化字符串。
        /// </summary>
        internal static string AttackMode_EnemyGuild {
            get {
                return ResourceManager.GetString("AttackMode_EnemyGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Mode: Group] 的本地化字符串。
        /// </summary>
        internal static string AttackMode_Group {
            get {
                return ResourceManager.GetString("AttackMode_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Mode: Guild] 的本地化字符串。
        /// </summary>
        internal static string AttackMode_Guild {
            get {
                return ResourceManager.GetString("AttackMode_Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Mode: Peaceful] 的本地化字符串。
        /// </summary>
        internal static string AttackMode_Peace {
            get {
                return ResourceManager.GetString("AttackMode_Peace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Mode: Red/Brown] 的本地化字符串。
        /// </summary>
        internal static string AttackMode_RedBrown {
            get {
                return ResourceManager.GetString("AttackMode_RedBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to connect to the server.{0}Attempt:{1} 的本地化字符串。
        /// </summary>
        internal static string AttemptingConnect {
            get {
                return ResourceManager.GetString("AttemptingConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto start 的本地化字符串。
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been poisoned 的本地化字符串。
        /// </summary>
        internal static string BeenPoisoned {
            get {
                return ResourceManager.GetString("BeenPoisoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BigMap ({0}) 的本地化字符串。
        /// </summary>
        internal static string BigMap {
            get {
                return ResourceManager.GetString("BigMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now blocking mentor requests. 的本地化字符串。
        /// </summary>
        internal static string BlockingMentorRequests {
            get {
                return ResourceManager.GetString("BlockingMentorRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block List 的本地化字符串。
        /// </summary>
        internal static string BlockList {
            get {
                return ResourceManager.GetString("BlockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot drop items on this map 的本地化字符串。
        /// </summary>
        internal static string CanNotDrop {
            get {
                return ResourceManager.GetString("CanNotDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use Dungeon Escapes here 的本地化字符串。
        /// </summary>
        internal static string CanNotDungeon {
            get {
                return ResourceManager.GetString("CanNotDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot leave game for {0} seconds 的本地化字符串。
        /// </summary>
        internal static string CannotLeaveGame {
            get {
                return ResourceManager.GetString("CannotLeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use Random Teleports here 的本地化字符串。
        /// </summary>
        internal static string CanNotRandom {
            get {
                return ResourceManager.GetString("CanNotRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use Resurrection Scrolls whilst alive 的本地化字符串。
        /// </summary>
        internal static string CannotResurrection {
            get {
                return ResourceManager.GetString("CannotResurrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character ({0}) 的本地化字符串。
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your character was created successfully. 的本地化字符串。
        /// </summary>
        internal static string CharacterCreated {
            get {
                return ResourceManager.GetString("CharacterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your character was deleted successfully. 的本地化字符串。
        /// </summary>
        internal static string CharacterDeleted {
            get {
                return ResourceManager.GetString("CharacterDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Character with this name already exists. 的本地化字符串。
        /// </summary>
        internal static string CharacterNameExists {
            get {
                return ResourceManager.GetString("CharacterNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string Chat_All {
            get {
                return ResourceManager.GetString("Chat_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Chat_Group {
            get {
                return ResourceManager.GetString("Chat_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild 的本地化字符串。
        /// </summary>
        internal static string Chat_Guild {
            get {
                return ResourceManager.GetString("Chat_Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lover 的本地化字符串。
        /// </summary>
        internal static string Chat_Lover {
            get {
                return ResourceManager.GetString("Chat_Lover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mentor 的本地化字符串。
        /// </summary>
        internal static string Chat_Mentor {
            get {
                return ResourceManager.GetString("Chat_Mentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shout 的本地化字符串。
        /// </summary>
        internal static string Chat_Short {
            get {
                return ResourceManager.GetString("Chat_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whisper 的本地化字符串。
        /// </summary>
        internal static string Chat_Whisper {
            get {
                return ResourceManager.GetString("Chat_Whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Settings 的本地化字符串。
        /// </summary>
        internal static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class Required : {0} 的本地化字符串。
        /// </summary>
        internal static string ClassRequired {
            get {
                return ResourceManager.GetString("ClassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close ({0}) 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find player {0} 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindPlayer {
            get {
                return ResourceManager.GetString("CouldNotFindPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Count {0} 的本地化字符串。
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating new characters is currently disabled. 的本地化字符串。
        /// </summary>
        internal static string CreatingCharactersDisabled {
            get {
                return ResourceManager.GetString("CreatingCharactersDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creatures ({0}) 的本地化字符串。
        /// </summary>
        internal static string Creatures {
            get {
                return ResourceManager.GetString("Creatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Credit 的本地化字符串。
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date Sent : {0} 的本地化字符串。
        /// </summary>
        internal static string DateSent {
            get {
                return ResourceManager.GetString("DateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DC + {0}~{1} (+{2}) 的本地化字符串。
        /// </summary>
        internal static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DC + {0}~{1} 的本地化字符串。
        /// </summary>
        internal static string DC2 {
            get {
                return ResourceManager.GetString("DC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to Delete the character {0} 的本地化字符串。
        /// </summary>
        internal static string DeleteCharacter {
            get {
                return ResourceManager.GetString("DeleteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have died, Do you want to revive in town? 的本地化字符串。
        /// </summary>
        internal static string DiedTip {
            get {
                return ResourceManager.GetString("DiedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Amount: 的本地化字符串。
        /// </summary>
        internal static string DropAmount {
            get {
                return ResourceManager.GetString("DropAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to drop {0}? 的本地化字符串。
        /// </summary>
        internal static string DropTip {
            get {
                return ResourceManager.GetString("DropTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Durability 的本地化字符串。
        /// </summary>
        internal static string Durability {
            get {
                return ResourceManager.GetString("Durability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dura Panel 的本地化字符串。
        /// </summary>
        internal static string DuraPanel {
            get {
                return ResourceManager.GetString("DuraPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the person you would like to mail. 的本地化字符串。
        /// </summary>
        internal static string EnterMailToName {
            get {
                return ResourceManager.GetString("EnterMailToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit ({0}) 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to quit Legend of Mir? 的本地化字符串。
        /// </summary>
        internal static string ExitTip {
            get {
                return ResourceManager.GetString("ExitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expanded Storage Expires On 的本地化字符串。
        /// </summary>
        internal static string ExpandedStorageExpiresOn {
            get {
                return ResourceManager.GetString("ExpandedStorageExpiresOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expanded Storage Locked 的本地化字符串。
        /// </summary>
        internal static string ExpandedStorageLocked {
            get {
                return ResourceManager.GetString("ExpandedStorageLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experience Gained {0} 的本地化字符串。
        /// </summary>
        internal static string ExperienceGained {
            get {
                return ResourceManager.GetString("ExperienceGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expire: {0} 的本地化字符串。
        /// </summary>
        internal static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expire: Never 的本地化字符串。
        /// </summary>
        internal static string ExpireNever {
            get {
                return ResourceManager.GetString("ExpireNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expire: Paused 的本地化字符串。
        /// </summary>
        internal static string ExpirePaused {
            get {
                return ResourceManager.GetString("ExpirePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to extend your rental period for 10 days at a cost of 1,000,000 gold? 的本地化字符串。
        /// </summary>
        internal static string ExtendYourRentalPeriod {
            get {
                return ResourceManager.GetString("ExtendYourRentalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you would like to unlock 4 extra slots? for gold: {0:###,###} 的本地化字符串。
        /// </summary>
        internal static string ExtraSlots4 {
            get {
                return ResourceManager.GetString("ExtraSlots4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you would like to buy 8 extra slots for 1,000,000 gold? Next purchase you can unlock 4 extra slots up to a maximum of 40 slots. 的本地化字符串。
        /// </summary>
        internal static string ExtraSlots8 {
            get {
                return ResourceManager.GetString("ExtraSlots8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to rent extra storage for 10 days at a cost of 1,000,000 gold? 的本地化字符串。
        /// </summary>
        internal static string ExtraStorage {
            get {
                return ResourceManager.GetString("ExtraStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must face someone to trade. 的本地化字符串。
        /// </summary>
        internal static string FaceToTrade {
            get {
                return ResourceManager.GetString("FaceToTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fishing ({0}) 的本地化字符串。
        /// </summary>
        internal static string Fishing {
            get {
                return ResourceManager.GetString("Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the person you would like to Add. 的本地化字符串。
        /// </summary>
        internal static string FriendEnterAddName {
            get {
                return ResourceManager.GetString("FriendEnterAddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the person you would like to Block. 的本地化字符串。
        /// </summary>
        internal static string FriendEnterBlockName {
            get {
                return ResourceManager.GetString("FriendEnterBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail 的本地化字符串。
        /// </summary>
        internal static string FriendMail {
            get {
                return ResourceManager.GetString("FriendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memo 的本地化字符串。
        /// </summary>
        internal static string FriendMemo {
            get {
                return ResourceManager.GetString("FriendMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friends ({0}) 的本地化字符串。
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whisper 的本地化字符串。
        /// </summary>
        internal static string FriendWhisper {
            get {
                return ResourceManager.GetString("FriendWhisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GameMaster 的本地化字符串。
        /// </summary>
        internal static string GameMaster {
            get {
                return ResourceManager.GetString("GameMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend of Mir 2 的本地化字符串。
        /// </summary>
        internal static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Shop ({0}) 的本地化字符串。
        /// </summary>
        internal static string GameShop {
            get {
                return ResourceManager.GetString("GameShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold 的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string GroupAdd {
            get {
                return ResourceManager.GetString("GroupAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the person you wish to add. 的本地化字符串。
        /// </summary>
        internal static string GroupAddEnterName {
            get {
                return ResourceManager.GetString("GroupAddEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string GroupRemove {
            get {
                return ResourceManager.GetString("GroupRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the person you wish to remove. 的本地化字符串。
        /// </summary>
        internal static string GroupRemoveEnterName {
            get {
                return ResourceManager.GetString("GroupRemoveEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Groups ({0}) 的本地化字符串。
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow/Disallow Group Requests 的本地化字符串。
        /// </summary>
        internal static string GroupSwitch {
            get {
                return ResourceManager.GetString("GroupSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild ({0}) 的本地化字符串。
        /// </summary>
        internal static string Guild {
            get {
                return ResourceManager.GetString("Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help ({0}) 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero Character ({0}) 的本地化字符串。
        /// </summary>
        internal static string HeroCharacter {
            get {
                return ResourceManager.GetString("HeroCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero Experience Gained {0} 的本地化字符串。
        /// </summary>
        internal static string HeroExperienceGained {
            get {
                return ResourceManager.GetString("HeroExperienceGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero Inventory ({0}) 的本地化字符串。
        /// </summary>
        internal static string HeroInventory {
            get {
                return ResourceManager.GetString("HeroInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero Skills ({0}) 的本地化字符串。
        /// </summary>
        internal static string HeroSkills {
            get {
                return ResourceManager.GetString("HeroSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Holy: + {0} (+{1}) 的本地化字符串。
        /// </summary>
        internal static string Holy {
            get {
                return ResourceManager.GetString("Holy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Holy: + {0} 的本地化字符串。
        /// </summary>
        internal static string Holy2 {
            get {
                return ResourceManager.GetString("Holy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect Password and AccountID combination. 的本地化字符串。
        /// </summary>
        internal static string IncorrectPasswordAccountID {
            get {
                return ResourceManager.GetString("IncorrectPasswordAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Character Name is not acceptable. 的本地化字符串。
        /// </summary>
        internal static string InvalidCharacterName {
            get {
                return ResourceManager.GetString("InvalidCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory ({0}) 的本地化字符串。
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory size increased. 的本地化字符串。
        /// </summary>
        internal static string InventoryIncreased {
            get {
                return ResourceManager.GetString("InventoryIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Description 的本地化字符串。
        /// </summary>
        internal static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common 的本地化字符串。
        /// </summary>
        internal static string ItemGradeCommon {
            get {
                return ResourceManager.GetString("ItemGradeCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heroic 的本地化字符串。
        /// </summary>
        internal static string ItemGradeHeroic {
            get {
                return ResourceManager.GetString("ItemGradeHeroic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legendary 的本地化字符串。
        /// </summary>
        internal static string ItemGradeLegendary {
            get {
                return ResourceManager.GetString("ItemGradeLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mythical 的本地化字符串。
        /// </summary>
        internal static string ItemGradeMythical {
            get {
                return ResourceManager.GetString("ItemGradeMythical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rare 的本地化字符串。
        /// </summary>
        internal static string ItemGradeRare {
            get {
                return ResourceManager.GetString("ItemGradeRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1}{2} {3} 的本地化字符串。
        /// </summary>
        internal static string ItemTextFormat {
            get {
                return ResourceManager.GetString("ItemTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amulet 的本地化字符串。
        /// </summary>
        internal static string ItemTypeAmulet {
            get {
                return ResourceManager.GetString("ItemTypeAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Armour 的本地化字符串。
        /// </summary>
        internal static string ItemTypeArmour {
            get {
                return ResourceManager.GetString("ItemTypeArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awakening 的本地化字符串。
        /// </summary>
        internal static string ItemTypeAwakening {
            get {
                return ResourceManager.GetString("ItemTypeAwakening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bait 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBait {
            get {
                return ResourceManager.GetString("ItemTypeBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bells 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBells {
            get {
                return ResourceManager.GetString("ItemTypeBells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Belt 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBelt {
            get {
                return ResourceManager.GetString("ItemTypeBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Book 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBook {
            get {
                return ResourceManager.GetString("ItemTypeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boots 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBoots {
            get {
                return ResourceManager.GetString("ItemTypeBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bracelet 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBracelet {
            get {
                return ResourceManager.GetString("ItemTypeBracelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CraftingMaterial 的本地化字符串。
        /// </summary>
        internal static string ItemTypeCraftingMaterial {
            get {
                return ResourceManager.GetString("ItemTypeCraftingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deco 的本地化字符串。
        /// </summary>
        internal static string ItemTypeDeco {
            get {
                return ResourceManager.GetString("ItemTypeDeco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finder 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFinder {
            get {
                return ResourceManager.GetString("ItemTypeFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fish 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFish {
            get {
                return ResourceManager.GetString("ItemTypeFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFloat {
            get {
                return ResourceManager.GetString("ItemTypeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFood {
            get {
                return ResourceManager.GetString("ItemTypeFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gem 的本地化字符串。
        /// </summary>
        internal static string ItemTypeGem {
            get {
                return ResourceManager.GetString("ItemTypeGem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Helmet 的本地化字符串。
        /// </summary>
        internal static string ItemTypeHelmet {
            get {
                return ResourceManager.GetString("ItemTypeHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hook 的本地化字符串。
        /// </summary>
        internal static string ItemTypeHook {
            get {
                return ResourceManager.GetString("ItemTypeHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mask 的本地化字符串。
        /// </summary>
        internal static string ItemTypeMask {
            get {
                return ResourceManager.GetString("ItemTypeMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meat 的本地化字符串。
        /// </summary>
        internal static string ItemTypeMeat {
            get {
                return ResourceManager.GetString("ItemTypeMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpawnEgg 的本地化字符串。
        /// </summary>
        internal static string ItemTypeMonsterSpawn {
            get {
                return ResourceManager.GetString("ItemTypeMonsterSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mount 的本地化字符串。
        /// </summary>
        internal static string ItemTypeMount {
            get {
                return ResourceManager.GetString("ItemTypeMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Necklace 的本地化字符串。
        /// </summary>
        internal static string ItemTypeNecklace {
            get {
                return ResourceManager.GetString("ItemTypeNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ore 的本地化字符串。
        /// </summary>
        internal static string ItemTypeOre {
            get {
                return ResourceManager.GetString("ItemTypeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pets 的本地化字符串。
        /// </summary>
        internal static string ItemTypePets {
            get {
                return ResourceManager.GetString("ItemTypePets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Potion 的本地化字符串。
        /// </summary>
        internal static string ItemTypePotion {
            get {
                return ResourceManager.GetString("ItemTypePotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quest 的本地化字符串。
        /// </summary>
        internal static string ItemTypeQuest {
            get {
                return ResourceManager.GetString("ItemTypeQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reel 的本地化字符串。
        /// </summary>
        internal static string ItemTypeReel {
            get {
                return ResourceManager.GetString("ItemTypeReel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reins 的本地化字符串。
        /// </summary>
        internal static string ItemTypeReins {
            get {
                return ResourceManager.GetString("ItemTypeReins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ribbon 的本地化字符串。
        /// </summary>
        internal static string ItemTypeRibbon {
            get {
                return ResourceManager.GetString("ItemTypeRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring 的本地化字符串。
        /// </summary>
        internal static string ItemTypeRing {
            get {
                return ResourceManager.GetString("ItemTypeRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saddle 的本地化字符串。
        /// </summary>
        internal static string ItemTypeSaddle {
            get {
                return ResourceManager.GetString("ItemTypeSaddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script 的本地化字符串。
        /// </summary>
        internal static string ItemTypeScript {
            get {
                return ResourceManager.GetString("ItemTypeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll 的本地化字符串。
        /// </summary>
        internal static string ItemTypeScroll {
            get {
                return ResourceManager.GetString("ItemTypeScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SealedHero 的本地化字符串。
        /// </summary>
        internal static string ItemTypeSealedHero {
            get {
                return ResourceManager.GetString("ItemTypeSealedHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stone 的本地化字符串。
        /// </summary>
        internal static string ItemTypeStone {
            get {
                return ResourceManager.GetString("ItemTypeStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Torch 的本地化字符串。
        /// </summary>
        internal static string ItemTypeTorch {
            get {
                return ResourceManager.GetString("ItemTypeTorch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform 的本地化字符串。
        /// </summary>
        internal static string ItemTypeTransform {
            get {
                return ResourceManager.GetString("ItemTypeTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon 的本地化字符串。
        /// </summary>
        internal static string ItemTypeWeapon {
            get {
                return ResourceManager.GetString("ItemTypeWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keybinds 的本地化字符串。
        /// </summary>
        internal static string Keybinds {
            get {
                return ResourceManager.GetString("Keybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Online 的本地化字符串。
        /// </summary>
        internal static string LastOnline {
            get {
                return ResourceManager.GetString("LastOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations! You have leveled up. Your HP and MP have been restored. 的本地化字符串。
        /// </summary>
        internal static string LevelUp {
            get {
                return ResourceManager.GetString("LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Out ({0}) 的本地化字符串。
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to log out of Legend of Mir? 的本地化字符串。
        /// </summary>
        internal static string LogOutTip {
            get {
                return ResourceManager.GetString("LogOutTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough DC. 的本地化字符串。
        /// </summary>
        internal static string LowDC {
            get {
                return ResourceManager.GetString("LowDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough gold. 的本地化字符串。
        /// </summary>
        internal static string LowGold {
            get {
                return ResourceManager.GetString("LowGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not a high enough level. 的本地化字符串。
        /// </summary>
        internal static string LowLevel {
            get {
                return ResourceManager.GetString("LowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Enough Mana to cast. 的本地化字符串。
        /// </summary>
        internal static string LowMana {
            get {
                return ResourceManager.GetString("LowMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough MC. 的本地化字符串。
        /// </summary>
        internal static string LowMC {
            get {
                return ResourceManager.GetString("LowMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough SC. 的本地化字符串。
        /// </summary>
        internal static string LowSC {
            get {
                return ResourceManager.GetString("LowSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luck + {0} 的本地化字符串。
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAC + {0}~{1} (+{2}) 的本地化字符串。
        /// </summary>
        internal static string MAC {
            get {
                return ResourceManager.GetString("MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAC + {0}~{1} 的本地化字符串。
        /// </summary>
        internal static string MAC2 {
            get {
                return ResourceManager.GetString("MAC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail 的本地化字符串。
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail Lover 的本地化字符串。
        /// </summary>
        internal static string MailLover {
            get {
                return ResourceManager.GetString("MailLover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Combine Count : {0}{1}Shift + Left click to split the stack 的本地化字符串。
        /// </summary>
        internal static string MaxCombine {
            get {
                return ResourceManager.GetString("MaxCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MC + {0}~{1} (+{2}) 的本地化字符串。
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MC + {0}~{1} 的本地化字符串。
        /// </summary>
        internal static string MC2 {
            get {
                return ResourceManager.GetString("MC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mentor ({0}) 的本地化字符串。
        /// </summary>
        internal static string Mentor {
            get {
                return ResourceManager.GetString("Mentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the person you would like to be your Mentor. 的本地化字符串。
        /// </summary>
        internal static string MentorEnterName {
            get {
                return ResourceManager.GetString("MentorEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow/Disallow Mentor Requests 的本地化字符串。
        /// </summary>
        internal static string MentorRequests {
            get {
                return ResourceManager.GetString("MentorRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu 的本地化字符串。
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mount ({0}) 的本地化字符串。
        /// </summary>
        internal static string Mount {
            get {
                return ResourceManager.GetString("Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never 的本地化字符串。
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New mail has arrived. 的本地化字符串。
        /// </summary>
        internal static string NewMail {
            get {
                return ResourceManager.GetString("NewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The AccountID does not exist. 的本地化字符串。
        /// </summary>
        internal static string NoAccountID {
            get {
                return ResourceManager.GetString("NoAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough space. 的本地化字符串。
        /// </summary>
        internal static string NoBagSpace {
            get {
                return ResourceManager.GetString("NoBagSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The class you selected does not exist. Contact a GM for assistance. 的本地化字符串。
        /// </summary>
        internal static string NoClass {
            get {
                return ResourceManager.GetString("NoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not own any creatures. 的本地化字符串。
        /// </summary>
        internal static string NoCreatures {
            get {
                return ResourceManager.GetString("NoCreatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not holding a fishing rod. 的本地化字符串。
        /// </summary>
        internal static string NoFishingRod {
            get {
                return ResourceManager.GetString("NoFishingRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t currently have a Mentorship to cancel. 的本地化字符串。
        /// </summary>
        internal static string NoMentorship {
            get {
                return ResourceManager.GetString("NoMentorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not own a mount. 的本地化字符串。
        /// </summary>
        internal static string NoMount {
            get {
                return ResourceManager.GetString("NoMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not Female. 的本地化字符串。
        /// </summary>
        internal static string NotFemale {
            get {
                return ResourceManager.GetString("NotFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not in a guild. 的本地化字符串。
        /// </summary>
        internal static string NotInGuild {
            get {
                return ResourceManager.GetString("NotInGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not Male. 的本地化字符串。
        /// </summary>
        internal static string NotMale {
            get {
                return ResourceManager.GetString("NotMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use Town Teleports here 的本地化字符串。
        /// </summary>
        internal static string NoTownTeleport {
            get {
                return ResourceManager.GetString("NoTownTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Players: {0} 的本地化字符串。
        /// </summary>
        internal static string OnlinePlayers {
            get {
                return ResourceManager.GetString("OnlinePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options ({0}) 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not get Patch Information 的本地化字符串。
        /// </summary>
        internal static string PatchErr {
            get {
                return ResourceManager.GetString("PatchErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Pet: Do Not Move] 的本地化字符串。
        /// </summary>
        internal static string PetMode_AttackOnly {
            get {
                return ResourceManager.GetString("PetMode_AttackOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Pet: Attack and Move] 的本地化字符串。
        /// </summary>
        internal static string PetMode_Both {
            get {
                return ResourceManager.GetString("PetMode_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Pet: Focus Master Target] 的本地化字符串。
        /// </summary>
        internal static string PetMode_FocusMasterTarget {
            get {
                return ResourceManager.GetString("PetMode_FocusMasterTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Pet: Do Not Attack] 的本地化字符串。
        /// </summary>
        internal static string PetMode_MoveOnly {
            get {
                return ResourceManager.GetString("PetMode_MoveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Pet: Do Not Attack or Move] 的本地化字符串。
        /// </summary>
        internal static string PetMode_None {
            get {
                return ResourceManager.GetString("PetMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quests ({0}) 的本地化字符串。
        /// </summary>
        internal static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranking ({0}) 的本地化字符串。
        /// </summary>
        internal static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relationship ({0}) 的本地化字符串。
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string RemoveFriend {
            get {
                return ResourceManager.GetString("RemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Mentor/Mentee 的本地化字符串。
        /// </summary>
        internal static string RemoveMentorMentee {
            get {
                return ResourceManager.GetString("RemoveMentorMentee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reply 的本地化字符串。
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request Divorce 的本地化字符串。
        /// </summary>
        internal static string RequestDivorce {
            get {
                return ResourceManager.GetString("RequestDivorce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request Marriage 的本地化字符串。
        /// </summary>
        internal static string RequestMarriage {
            get {
                return ResourceManager.GetString("RequestMarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required DC : {0} 的本地化字符串。
        /// </summary>
        internal static string RequiredDC {
            get {
                return ResourceManager.GetString("RequiredDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Level : {0} 的本地化字符串。
        /// </summary>
        internal static string RequiredLevel {
            get {
                return ResourceManager.GetString("RequiredLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required MC : {0} 的本地化字符串。
        /// </summary>
        internal static string RequiredMC {
            get {
                return ResourceManager.GetString("RequiredMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required SC : {0} 的本地化字符串。
        /// </summary>
        internal static string RequiredSC {
            get {
                return ResourceManager.GetString("RequiredSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution 的本地化字符串。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rested{0}Increases Exp Rate by {1}%{2} 的本地化字符串。
        /// </summary>
        internal static string RestedBuff {
            get {
                return ResourceManager.GetString("RestedBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate 的本地化字符串。
        /// </summary>
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SC + {0}~{1} (+{2}) 的本地化字符串。
        /// </summary>
        internal static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SC + {0}~{1} 的本地化字符串。
        /// </summary>
        internal static string SC2 {
            get {
                return ResourceManager.GetString("SC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the Key for: {0} 的本地化字符串。
        /// </summary>
        internal static string SelectKey {
            get {
                return ResourceManager.GetString("SelectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected: Server is shutting down. 的本地化字符串。
        /// </summary>
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills ({0}) 的本地化字符串。
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The spirits of fire disappeared. 的本地化字符串。
        /// </summary>
        internal static string SpiritsFireDisappeared {
            get {
                return ResourceManager.GetString("SpiritsFireDisappeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow/Block Marriage 的本地化字符串。
        /// </summary>
        internal static string SwitchMarriage {
            get {
                return ResourceManager.GetString("SwitchMarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taoists are well disciplined in the study of Astronomy, Medicine, and others aside from Mu-Gong. Rather then directly engaging the enemies, their specialty lies in assisting their allies with support. Taoists can summon powerful creatures and have a high resistance to magic, and is a class with well balanced offensive and defensive abilities. 的本地化字符串。
        /// </summary>
        internal static string TaoistDes {
            get {
                return ResourceManager.GetString("TaoistDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot make anymore then {0} Characters. 的本地化字符串。
        /// </summary>
        internal static string ToManyCharacters {
            get {
                return ResourceManager.GetString("ToManyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is too heavy to Hold. 的本地化字符串。
        /// </summary>
        internal static string TooHeavyToHold {
            get {
                return ResourceManager.GetString("TooHeavyToHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade ({0}) 的本地化字符串。
        /// </summary>
        internal static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        internal static string Usrname {
            get {
                return ResourceManager.GetString("Usrname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warriors are a class of great strength and vitality. They are not easily killed in battle and have the advantage of being able to use a variety of heavy weapons and Armour. Therefore, Warriors favor attacks that are based on melee physical damage. They are weak in ranged attacks, however the variety of equipment that are developed specifically for Warriors complement their weakness in ranged combat. 的本地化字符串。
        /// </summary>
        internal static string WarriorsDes {
            get {
                return ResourceManager.GetString("WarriorsDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Curse dwells within your weapon. 的本地化字符串。
        /// </summary>
        internal static string WeaponCurse {
            get {
                return ResourceManager.GetString("WeaponCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luck dwells within your weapon. 的本地化字符串。
        /// </summary>
        internal static string WeaponLuck {
            get {
                return ResourceManager.GetString("WeaponLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No effect. 的本地化字符串。
        /// </summary>
        internal static string WeaponNoEffect {
            get {
                return ResourceManager.GetString("WeaponNoEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your weapon is glowed by spirit of fire. 的本地化字符串。
        /// </summary>
        internal static string WeaponSpiritFire {
            get {
                return ResourceManager.GetString("WeaponSpiritFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeddingRing 的本地化字符串。
        /// </summary>
        internal static string WeddingRing {
            get {
                return ResourceManager.GetString("WeddingRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W: 的本地化字符串。
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to the {0} Server. 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whisper Lover 的本地化字符串。
        /// </summary>
        internal static string WhisperLover {
            get {
                return ResourceManager.GetString("WhisperLover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wizards are a class of low strength and stamina, but have the ability to use powerful spells. Their offensive spells are very effective, but because it takes time to cast these spells, they&apos;re likely to leave themselves open for enemy&apos;s attacks. Therefore, the physically weak wizards must aim to attack their enemies from a safe distance. 的本地化字符串。
        /// </summary>
        internal static string WizardDes {
            get {
                return ResourceManager.GetString("WizardDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You gained {0}. 的本地化字符串。
        /// </summary>
        internal static string YouGained {
            get {
                return ResourceManager.GetString("YouGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You gained {0:###,###,###} {1} 的本地化字符串。
        /// </summary>
        internal static string YouGained2 {
            get {
                return ResourceManager.GetString("YouGained2", resourceCulture);
            }
        }
    }
}
